name: googleapis_generator_dependency
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  discoveryapis_generator:
    path: ../discoveryapis_generator
  io: ^0.3.3
  pool: ^1.4.0
  yaml: ^2.1.0
