packages:
- googleapis:
    version: 0.23.0
    author: Dart Team <misc@dartlang.org>
    homepage: http://www.dartlang.org/googleapis/
    readme: resources/README.md
    license: resources/LICENSE
    changelog: resources/googleapis/CHANGELOG.md
    apis:
    - adexchangebuyer:v1.3  # https://developers.google.com/ad-exchange/buyer-rest/
    - adexchangebuyer:v1.4  # https://developers.google.com/ad-exchange/buyer-rest/
    - adexchangeseller:v1.1  # https://developers.google.com/ad-exchange/seller-rest/
    - adexchangeseller:v2.0  # https://developers.google.com/ad-exchange/seller-rest/
    - admin:datatransfer_v1 # https://developers.google.com/admin-sdk/data-transfer/
    - admin:directory_v1  # https://developers.google.com/admin-sdk/directory/
    - admin:email_migration_v2  #https://developers.google.com/admin-sdk/email-migration/
    - admin:reports_v1  # https://developers.google.com/admin-sdk/reports/
    - adsensehost:v4.1  # https://developers.google.com/adsense/host/
    - adsense:v1.4  # https://developers.google.com/adsense/management/
    - analytics:v3  # https://developers.google.com/analytics/
    - androidenterprise:v1 # https://developers.google.com/api-client-library/java/apis/androidenterprise/v1
    - androidpublisher:v2  # https://developers.google.com/android-publisher/
    - appsactivity:v1  # https://developers.google.com/google-apps/activity/
    - appstate:v1  # https://developers.google.com/games/services/web/api/states
    - bigquery:v2  # https://developers.google.com/bigquery/
    - blogger:v3  # https://developers.google.com/blogger/
    - books:v1  # https://developers.google.com/books/
    - calendar:v3  # https://developers.google.com/google-apps/calendar/
    - civicinfo:v2  # https://developers.google.com/civic-information/
    - classroom:v1  # https://developers.google.com/classroom/
    - cloudbilling:v1 # https://cloud.google.com/billing/
    - clouddebugger:v2 # https://cloud.google.com/tools/cloud-debugger
    - cloudlatencytest:v2
    - cloudtrace:v1 # https://cloud.google.com/cloud-trace/
    - compute:v1  # https://developers.google.com/compute/
    - container:v1
    - content:v2  # https://developers.google.com/shopping-content/
    - content:v2sandbox
    - coordinate:v1  # https://google-developers.appspot.com/coordinate/
    - customsearch:v1  # https://developers.google.com/custom-search/
    - dataproc:v1 # https://cloud.google.com/dataproc/
    - deploymentmanager:v2
    - dfareporting:v1.3  # https://developers.google.com/doubleclick-advertisers/reporting/
    - dfareporting:v2.0  # https://developers.google.com/doubleclick-advertisers/reporting/
    - dfareporting:v2.1  # https://developers.google.com/doubleclick-advertisers/reporting/
    - dfareporting:v2.2  # https://developers.google.com/doubleclick-advertisers/reporting/
    - dfareporting:v2.3  # https://developers.google.com/doubleclick-advertisers/reporting/
    - discovery:v1  # https://developers.google.com/discovery/
    - dns:v1  # https://cloud.google.com/dns/api/v1/
    - doubleclickbidmanager:v1  # https://developers.google.com/bid-manager/
    - doubleclicksearch:v2  # https://developers.google.com/doubleclick-search/
    - drive:v2  # https://developers.google.com/drive/v2/reference/
    - drive:v3  # https://developers.google.com/drive/v3/reference/
    - fitness:v1  # https://developers.google.com/fitness/
    - freebase:v1  # https://developers.google.com/freebase/
    - fusiontables:v1  # https://developers.google.com/fusiontables/
    - fusiontables:v2  # https://developers.google.com/fusiontables/
    - gamesConfiguration:v1configuration  # https://developers.google.com/games/services/publishing/api/
    - gamesManagement:v1management  # https://developers.google.com/games/services/management/api/
    - games:v1  # https://developers.google.com/games/services/
    - genomics:v1 # https://cloud.google.com/genomics/
    - gmail:v1  # https://developers.google.com/gmail/
    - groupsmigration:v1  # https://developers.google.com/admin-sdk/groups-migration/
    - groupssettings:v1  # https://developers.google.com/admin-sdk/groups-settings/
    - identitytoolkit:v3  # https://developers.google.com/identity-toolkit/
    - kgsearch:v1  # https://developers.google.com/knowledge-graph/
    - licensing:v1  # https://developers.google.com/admin-sdk/licensing/v1/how-tos/using
    - mapsengine:v1  # https://developers.google.com/maps-engine/
    - mirror:v1  # https://developers.google.com/glass/develop/mirror/
    - oauth2:v2  # https://developers.google.com/accounts/docs/OAuth2UserAgent
    - pagespeedonline:v1  # https://developers.google.com/speed/docs/insights/about
    - pagespeedonline:v2  # https://developers.google.com/speed/docs/insights/about
    - partners:v2  # https://developers.google.com/partners/
    - playmoviespartner:v1
    - plusDomains:v1  # https://developers.google.com/+/domains/
    - plus:v1  # https://developers.google.com/+/api/
    - prediction:v1.6  # https://developers.google.com/prediction/
    - pubsub:v1  # https://cloud.google.com/pubsub/
    - qpxExpress:v1  # https://developers.google.com/qpx-express/
    - reseller:v1  # https://developers.google.com/admin-sdk/reseller/
    - reseller:v1sandbox
    - script:v1  # https://developers.google.com/apps-script/execution/rest/v1/run
    - siteVerification:v1  # https://developers.google.com/site-verification/
    - storagetransfer:v1  # https://cloud.google.com/storage/transfer/
    - storage:v1  # https://developers.google.com/storage/
    - tagmanager:v1  # https://developers.google.com/tag-manager/
    - tasks:v1  # https://developers.google.com/google-apps/tasks/
    - translate:v2  # https://developers.google.com/translate/
    - urlshortener:v1  # https://developers.google.com/url-shortener/
    - webfonts:v1  # https://developers.google.com/fonts/docs/developer_api
    - webmasters:v3  # https://developers.google.com/webmaster-tools/
    - youtubeAnalytics:v1  # https://developers.google.com/youtube/analytics/
    - youtubereporting:v1  # https://developers.google.com/youtube/reporting/v1/reports/
    - youtube:v3  # https://developers.google.com/youtube/

- googleapis_beta:
    version: 0.23.2
    author: Dart Team <misc@dartlang.org>
    homepage: http://www.dartlang.org/googleapis/
    readme: resources/README.md
    license: resources/LICENSE
    changelog: resources/googleapis_beta/CHANGELOG.md
    apis:
    - appengine:v1beta4
    - autoscaler:v1beta2  # https://developers.google.com/compute/docs/autoscaler/ (Limited Preview)
    - cloudmonitoring:v2beta2  # https://developers.google.com/cloud-monitoring/
    - cloudresourcemanager:v1beta1
    - clouduseraccounts:beta # https://cloud.google.com/compute/docs/access/user-accounts/api/latest/
    - dataflow:v1b3  # https://cloud.google.com/dataflow/
    - datastore:v1beta2  # https://developers.google.com/datastore/
    - dataproc:v1beta1 # https://cloud.google.com/dataproc/
    - deploymentmanager:v2beta1  # https://cloud.google.com/deployment-manager/
    - deploymentmanager:v2beta2  # https://cloud.google.com/deployment-manager/
    - genomics:v1beta2  # https://developers.google.com/genomics/
    - logging:v2beta1 # https://cloud.google.com/appengine/articles/logging
    - manager:v1beta2  # https://developers.google.com/deployment-manager/
    - proximitybeacon:v1beta1  # https://developers.google.com/beacons/proximity/guides
    - pubsub:v1beta2  # https://developers.google.com/pubsub/ (Limited Preview)
    - replicapoolupdater:v1beta1  # https://cloud.google.com/compute/docs/instance-groups/manager/
    - replicapool:v1beta2  # https://cloud.google.com/compute/docs/instance-groups/manager/
    - resourceviews:v1beta1  # https://cloud.google.com/compute/docs/instance-groups/ (Limited Preview)
    - resourceviews:v1beta2  # https://cloud.google.com/compute/docs/instance-groups/
    - sqladmin:v1beta3  # https://developers.google.com/cloud-sql/docs/admin-api/
    - sqladmin:v1beta4  # https://developers.google.com/cloud-sql/docs/admin-api/
    - taskqueue:v1beta2  # https://developers.google.com/appengine/docs/python/taskqueue/rest/libraries

skipped_apis:
- adexchangebuyer:v1.2  # v1.3 included
- adexchangeseller:v1  # v1.1 included
- adsense:v1.2  # v1.4 included
- adsense:v1.3  # v1.4 included
- analytics:v2.4  # v3 included
- androidpublisher:v1.1  # v2 included
- androidpublisher:v1  # v2 included
- blogger:v2  # v3 included
- clouduseraccounts:alpha  # Leave out alpha versions for now
- clouduseraccounts:vm_alpha  # Leave out alpha versions for now
- clouduseraccounts:vm_beta # seems to be the same API as "beta"
- datastore:v1beta1  # v1beta2 included
- dataproc:v1alpha1 # v1beta1 included
- dfareporting:v1.1  # v1.3 included
- dfareporting:v1.2  # v1.3 included
- dfareporting:v1  # v1.3 included
- drive:v1  # v2 included
- gan:v1beta1  # Deprecated as of April 16, 2013, https://developers.google.com/affiliate-network/
- mapsengine:exp2  # v1 included
- oauth2:v1  # v2 included
- prediction:v1.2  # v1.6 included
- prediction:v1.3  # v1.6 included
- prediction:v1.4  # v1.6 included
- prediction:v1.5  # v1.6 included
- pubsub:v1beta1a  # v1beta1, v1bets2 and v1 included
- replicapool:v1beta1  # Deprecated
- spectrum:v1explorer  # Not included, https://developers.google.com/spectrum/
- storage:v1beta1  # v1 included
- storage:v1beta2  # v1 included
- taskqueue:v1beta1  # v1beta2 included
- youtubeAnalytics:v1beta1  # v1 included
