packages:
- googleapis:
    version: 0.10.0
    author: Dart Team <misc@dartlang.org>
    homepage: http://www.dartlang.org/googleapis/
    readme: resources/README.md
    license: resources/LICENSE
    changelog: resources/googleapis/CHANGELOG.md
    apis:
    - adexchangebuyer:v1.3  # https://developers.google.com/ad-exchange/buyer-rest/
    - adexchangeseller:v1.1  # https://developers.google.com/ad-exchange/seller-rest/
    - adexchangeseller:v2.0  # https://developers.google.com/ad-exchange/seller-rest/
    - admin:directory_v1  # https://developers.google.com/admin-sdk/directory/
    - admin:email_migration_v2  #https://developers.google.com/admin-sdk/email-migration/
    - admin:reports_v1  # https://developers.google.com/admin-sdk/reports/
    - adsense:v1.4  # https://developers.google.com/adsense/management/
    - adsensehost:v4.1  # https://developers.google.com/adsense/host/
    - analytics:v3  # https://developers.google.com/analytics/
    - androidenterprise:v1 # https://developers.google.com/api-client-library/java/apis/androidenterprise/v1
    - androidpublisher:v2  # https://developers.google.com/android-publisher/
    - appsactivity:v1  # https://developers.google.com/google-apps/activity/
    - appstate:v1  # https://developers.google.com/games/services/web/api/states
    - bigquery:v2  # https://developers.google.com/bigquery/
    - blogger:v3  # https://developers.google.com/blogger/
    - books:v1  # https://developers.google.com/books/
    - civicinfo:v2  # https://developers.google.com/civic-information/
    - calendar:v3  # https://developers.google.com/google-apps/calendar/
    - compute:v1  # https://developers.google.com/compute/
    - content:v2  # https://developers.google.com/shopping-content/
    - coordinate:v1  # https://google-developers.appspot.com/coordinate/
    - customsearch:v1  # https://developers.google.com/custom-search/
    - discovery:v1  # https://developers.google.com/discovery/
    - drive:v2  # https://developers.google.com/drive/v2/reference/
    - dfareporting:v1.3  # https://developers.google.com/doubleclick-advertisers/reporting/
    - dfareporting:v2.0  # https://developers.google.com/doubleclick-advertisers/reporting/
    - doubleclickbidmanager:v1  # https://developers.google.com/bid-manager/
    - doubleclicksearch:v2  # https://developers.google.com/doubleclick-search/
    - fitness:v1  # https://developers.google.com/fitness/
    - freebase:v1  # https://developers.google.com/freebase/
    - fusiontables:v1  # https://developers.google.com/fusiontables/
    - fusiontables:v2  # https://developers.google.com/fusiontables/
    - games:v1  # https://developers.google.com/games/services/
    - gamesConfiguration:v1configuration  # https://developers.google.com/games/services/publishing/api/
    - gamesManagement:v1management  # https://developers.google.com/games/services/management/api/
    - gmail:v1  # https://developers.google.com/gmail/
    - groupsmigration:v1  # https://developers.google.com/admin-sdk/groups-migration/
    - groupssettings:v1  # https://developers.google.com/admin-sdk/groups-settings/
    - identitytoolkit:v3  # https://developers.google.com/identity-toolkit/
    - licensing:v1  # https://developers.google.com/admin-sdk/licensing/v1/how-tos/using
    - mapsengine:v1  # https://developers.google.com/maps-engine/
    - mirror:v1  # https://developers.google.com/glass/develop/mirror/
    - oauth2:v2  # https://developers.google.com/accounts/docs/OAuth2UserAgent
    - pagespeedonline:v1  # https://developers.google.com/speed/docs/insights/about
    - pagespeedonline:v2  # https://developers.google.com/speed/docs/insights/about
    - plus:v1  # https://developers.google.com/+/api/
    - plusDomains:v1  # https://developers.google.com/+/domains/
    - prediction:v1.6  # https://developers.google.com/prediction/
    - qpxExpress:v1  # https://developers.google.com/qpx-express/
    - reseller:v1  # https://developers.google.com/admin-sdk/reseller/
    - siteVerification:v1  # https://developers.google.com/site-verification/
    - storage:v1  # https://developers.google.com/storage/
    - tagmanager:v1  # https://developers.google.com/tag-manager/
    - tasks:v1  # https://developers.google.com/google-apps/tasks/
    - translate:v2  # https://developers.google.com/translate/
    - urlshortener:v1  # https://developers.google.com/url-shortener/
    - webfonts:v1  # https://developers.google.com/fonts/docs/developer_api
    - webmasters:v3  # https://developers.google.com/webmaster-tools/
    - youtube:v3  # https://developers.google.com/youtube/
    - youtubeAnalytics:v1  # https://developers.google.com/youtube/analytics/

- googleapis_beta:
    version: 0.14.0
    author: Dart Team <misc@dartlang.org>
    homepage: http://www.dartlang.org/googleapis/
    readme: resources/README.md
    license: resources/LICENSE
    changelog: resources/googleapis_beta/CHANGELOG.md
    apis:
    - autoscaler:v1beta2  # https://developers.google.com/compute/docs/autoscaler/ (Limited Preview)
    - cloudmonitoring:v2beta2  # https://developers.google.com/cloud-monitoring/
    - container:v1beta1  #
    - datastore:v1beta2  # https://developers.google.com/datastore/
    - deploymentmanager:v2beta1  # https://cloud.google.com/deployment-manager/
    - dns:v1beta1  # https://developers.google.com/cloud-dns/
    - genomics:v1beta2  # https://developers.google.com/genomics/
    - logging:v1beta3 # https://cloud.google.com/appengine/articles/logging
    - manager:v1beta2  # https://developers.google.com/deployment-manager/
    - pubsub:v1beta1  # https://developers.google.com/pubsub/ (Limited Preview)
    - pubsub:v1beta2  # https://developers.google.com/pubsub/ (Limited Preview)
    - replicapool:v1beta2  # https://cloud.google.com/compute/docs/instance-groups/manager/
    - replicapoolupdater:v1beta1  # https://cloud.google.com/compute/docs/instance-groups/manager/
    - resourceviews:v1beta1  # https://cloud.google.com/compute/docs/instance-groups/ (Limited Preview)
    - resourceviews:v1beta2  # https://cloud.google.com/compute/docs/instance-groups/
    - sqladmin:v1beta3  # https://developers.google.com/cloud-sql/docs/admin-api/
    - sqladmin:v1beta4  # https://developers.google.com/cloud-sql/docs/admin-api/
    - taskqueue:v1beta2  # https://developers.google.com/appengine/docs/python/taskqueue/rest/libraries

skipped_apis:
