name: googleapis_generator_dependency
version: 0.1.0
author: Dart Team
description: A dart package for pin-pointing the version of the generator used to generate APIs.
dependencies:
  discoveryapis_generator: '>=0.6.0 <0.7.0'